apiVersion: v1
kind: Secret
metadata:
  name: jfrogcred
  namespace: valaxy
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJ0cmlhbHlqaHJ2bi5qZnJvZy5pbyI6IHsKCQkJImF1dGgiOiAiWkc5amEyVnlZM0psWkdzNE9rRnVhWEoxWkdoQU1ETT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
